#!/bin/bash
network="devnet"
config_file=$(</mnt/c/Users/kevin/OneDrive/Documents/Other/Solana/NFT/metaplex-master/.cache/$network-temp)
echo $config_file
exit 1
cd candy-machine-mint-main
#pub_key=3wjPc8oPpECxoxReVsfYe15YLeHFq196YRfb99pZtLyS
#cm_address=J9FEAafLEEico4TKtb1E5Dzf8rk9KMvdy3tkAN87pdVL
#start_date=1637856000
#config=9FoAVdZ3vjVn1GezAJxUYryJA3W17T1z9fvYQ4tFoSDo

config_file=$(</mnt/c/Users/kevin/OneDrive/Documents/Other/Solana/NFT/metaplex-master/.cache/devnet-temp)
config=$(echo $config_file | grep -o -P 'config.{48}'| cut -c10-52)
pub_key=$(echo $config_file | grep -o -P 'authority.{48}'| cut -c13-56)
cm_address=$(echo $config_file | grep -o -P 'candyMachineAddress.{66}'| cut -c23-66)
start_date=$(echo $config_file | grep -o -P 'startDate.{12}' | cut -c12-66)

echo "REACT_APP_CANDY_MACHINE_CONFIG=$config" >| .env
echo "REACT_APP_CANDY_MACHINE_ID=$cm_address" >> .env
echo "REACT_APP_TREASURY_ADDRESS=$pub_key" >> .env
echo "REACT_APP_CANDY_START_DATE=$start_date" >>  .env
echo -e "\n" >> .env
echo "REACT_APP_SOLANA_NETWORK=$network" >> .env
echo "REACT_APP_SOLANA_RPC_HOST=https://explorer-api.$network.solana.com"
